language: php

php:
  - "7.1"
  - "7.2"

before_script:
  - cp .env.example .env
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install --no-autoloader
  - composer update -n

script:
  - php vendor/bin/phpunit

branches:
  only:
    - master